# Generated by Django 4.2.5 on 2023-09-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length='25', verbose_name='Имя')),
                ('tel', models.TextField(max_length='12', verbose_name='Телефон')),
                ('comments', models.TextField(max_length='250', verbose_name='Комментарий')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата заявки')),
            ],
        ),
    ]
